name: the28awg
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  path_to_regexp: ^0.4.0
  cyclop: ^0.5.2
  flutter_bloc: ^8.0.1
  path_provider: ^2.0.11
  equatable: ^2.0.3
  provider: ^6.0.3
  jiffy: ^5.0.0
  freezed_annotation: ^2.1.0
  json_serializable: ^6.3.1
  google_fonts: ^3.0.1
  flutter_native_splash: ^2.2.7
  auto_route: ^4.2.1
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.2.0
  analyzer: ^4.4.0
  freezed: ^2.1.0+1
  dart_code_metrics: ^4.17.0
  auto_route_generator: ^4.2.1

dependency_overrides:
  analyzer: ^4.4.0
  path: ^1.8.2
  test_api: ^0.4.12
  petitparser: ^5.0.0

flutter:
  uses-material-design: true

flutter_intl:
  main_locale: ru
  enabled: true